import {useState} from 'react';
import './DashboardData.css';
const fmt=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
const colors=['#10b981','#3b82f6','#f59e0b'];
function Chart({rows,keys}){
 if(!rows.length)return <p>Add records to see the line chart.</p>;
 const vals=rows.flatMap(r=>keys.map(([k])=>Number(r[k]||0))),lo=Math.min(0,...vals),hi=Math.max(1,...vals),span=hi-lo||1;
 const first=Date.parse(rows[0].date),last=Date.parse(rows.at(-1).date),x=r=>65+(Date.parse(r.date)-first)/(last-first||1)*660,y=v=>185-(Number(v||0)-lo)/span*150;
 return <><svg viewBox="0 0 790 230" role="img" aria-label={keys.map(k=>k[1]).join(', ')+' recorded trend'}>{[0,.5,1].map(t=><g key={t}><line x1="65" x2="725" y1={185-t*150} y2={185-t*150} stroke="currentColor" opacity=".15"/><text x="60" y={189-t*150} textAnchor="end">{fmt(lo+t*span)}</text></g>)}{keys.map(([k,label],i)=><g key={k}><polyline points={rows.map(r=>`${x(r)},${y(r[k])}`).join(' ')} fill="none" stroke={colors[i]} strokeWidth="3"/>{rows.map((r,j)=><circle key={j} cx={x(r)} cy={y(r[k])} r="4" fill={colors[i]}><title>{r.date}: {label} {fmt(r[k])}</title></circle>)}</g>)}<text x="65" y="220">{rows[0].date}</text><text x="725" y="220" textAnchor="end">{rows.at(-1).date}</text></svg><div className="dd-legend">{keys.map(([k,label],i)=><span key={k}><i style={{background:colors[i]}}/>{label}</span>)}</div><p className="dd-note">Recorded dates only. Lines connect observations; missing dates are not zero.</p></>;
}
function Records({rows,columns}){
 const [page,setPage]=useState(0),pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages-1);
 return <details><summary>View all {rows.length} records</summary><div className="dd-table"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{[...rows].reverse().slice(current*10,current*10+10).map((r,i)=><tr key={r.id||i}>{columns.map(([k])=><td key={k}>{r[k]??'—'}</td>)}</tr>)}</tbody></table></div>{pages>1&&<div className="dd-pages"><button disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1} / {pages}</span><button disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</button></div>}</details>;
}
const sorted=(rows,key)=>rows.map(r=>({...r,date:String(r[key]||r.created_at||'').slice(0,10)})).filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.date)).sort((a,b)=>a.date.localeCompare(b.date));
function daily(rows,keys,average=false){const map=new Map();for(const r of rows){if(!map.has(r.date))map.set(r.date,{date:r.date,count:0,...Object.fromEntries(keys.map(k=>[k,0]))});const d=map.get(r.date);d.count++;keys.forEach(k=>d[k]+=Number(r[k]||0));}return [...map.values()].map(d=>({...d,...Object.fromEntries(keys.map(k=>[k,average?d[k]/d.count:d[k]]))}));}
const Stats=({items})=><div className="dd-stats">{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;
export default function DashboardData({financial,study,habits,setCurrentRoute}){
 const f=sorted(financial,'created_at'),s=sorted(study,'study_date'),h=sorted(habits,'record_date'),latest=f.at(-1),sd=daily(s,['study_hours']),hd=daily(h,['sleep_hours','screen_time','exercise_minutes'],true);
 const avg=k=>hd.length?fmt(hd.reduce((n,r)=>n+r[k],0)/hd.length):'—';
 const [metric,setMetric]=useState('sleep_hours');const labels={sleep_hours:'Sleep (hours)',screen_time:'Screen time (hours)',exercise_minutes:'Exercise (minutes)'};
 const header=(title,subtitle,route)=><header><div><h2>{title}</h2><p>{subtitle}</p></div><button className="btn btn-secondary" onClick={()=>setCurrentRoute(route)}>Add / manage records →</button></header>;
 return <div className="dashboard-data"><section className="card dd-section">{header('Financial overview','Income, expenses and savings · saved currency units','financial')}<Stats items={['income','expenses','savings'].map(k=>['Latest monthly '+k,latest?fmt(latest['monthly_'+k]):'—'])}/><Chart rows={f} keys={['income','expenses','savings'].map(k=>['monthly_'+k,k])}/><Records rows={f} columns={[["date","Date"],["monthly_income","Income"],["monthly_expenses","Expenses"],["monthly_savings","Savings"],["financial_goal","Goal"]]}/></section>
 <section className="card dd-section">{header('Study overview','Study sessions and daily study time','study')}<Stats items={[["Total hours",fmt(s.reduce((n,r)=>n+Number(r.study_hours||0),0))],["Sessions",study.length],["Recorded days",sd.length]]}/><Chart rows={sd} keys={[["study_hours","Study hours per recorded day"]]}/><Records rows={s} columns={[["date","Date"],["study_hours","Hours"],["subjects","Subjects"],["academic_goal","Goal"]]}/></section>
 <section className="card dd-section">{header('Habit overview','Sleep, screen time and exercise · recorded-day averages','habit')}<Stats items={[["Sleep / day",avg('sleep_hours')+' hrs'],["Screen / day",avg('screen_time')+' hrs'],["Exercise / day",avg('exercise_minutes')+' min']]}/><label>Chart metric <select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><Chart rows={hd} keys={[[metric,labels[metric]]]}/><Records rows={h} columns={[["date","Date"],["sleep_hours","Sleep (hrs)"],["screen_time","Screen (hrs)"],["exercise_minutes","Exercise (min)"],["habit_notes","Notes"]]}/></section></div>;
}
